### ISSUE TITLE
Remove no anda

### ISSUE THREAD

**Issue by dadais216** [tgc-utn/tgc-tools#9]
cuando selecciono una mesh y toco remove la mesh no se borra, y se crea una copia de esta en su posición original 

Se puede comprobar facilmente creando un mesh, transladando, y removiendo.

**Comment by rejurime** [comment]
En el mesh creator te pasa esto? o en alguna otra herramienta?
Con que mesh te pasa? caja, esfera todos?
Cuando hablas de remover, es la funcionalidad delete object? intente reproducirlo y me funciona por eso las preguntas para llegar al mismo caso.

**Comment by dadais216** [comment]
Hola, me olvide de aclarar que esto pasa en el Scene editor, el mesh creator anda bien. Parece ser que las dos herramientas hacen lo mismo asi que termine usando el mesh creator y no tuve problemas.

Para replicarlo abri el scene editor, importe Box-TgcScene.xml, traslade y removi. 

Saludos
